config/routes.rb
Rails.application.routes.draw do
  resources :pins

	root "pages#home"
	get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = Pin.new
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>218 Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <%= csrf_meta_tags %>
  <style>
  	.pintest{
  		color: black;

  	}
	.address{
	    width: 100%; 
		height: 100%;
		margin: 0px;  
		font-size: 15px;
		background-color: rgb(0,0,0,.5); 
		padding: 0px;
		margin-top: 300px;
	}
	table { 
		border-spacing: 100px;
		border-collapse: separate;
	}
	
	.menu {
		-webkit-column-count: 3; /* Chrome, Safari, Opera */
		-moz-column-count: 3; /* Firefox */
		column-count: 3;

		-webkit-column-gap: 40px; /* Chrome, Safari, Opera */
		-moz-column-gap: 40px; /* Firefox */
		column-gap: 40px;
	}
  </style>
</head>
<body>
    <div class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm">
      <a class="navmenu-brand visible-md visible-lg" href="#"><font face="verdana" size="7" color="white">迎 218 旺</font></a>
	  <a class="navmenu-brand visible-md visible-lg" href="#"><font face="verdana" size="9" color="white">Restaurant</font></a>

	  <hr><br>
		  <center>
		  <div class="menu-bar" data-example-id="simple-nav-stacked">
			<ul class="nav nav-pills nav-stacked red">
			  <li role="presentation" class="active"><a href="#">Menu</a></li>
			  <li role="presentation"><a href="#">Lunch</a></li>
			  <li role="presentation"><a href="#">Dinner</a></li>
			</ul>
			<div id="toc" class="toc">
<div id="toctitle">
<h2>Contents</h2>
</div>
<ul>
<li class="toclevel-1 tocsection-1"><a href="#Life_and_career"><span class="tocnumber">1</span> <span class="toctext">Life and career</span></a></li>
<li class="toclevel-1 tocsection-2"><a href="#Personal_life"><span class="tocnumber">2</span> <span class="toctext">Personal life</span></a></li>
<li class="toclevel-1 tocsection-3"><a href="#Discography"><span class="tocnumber">3</span> <span class="toctext">Discography</span></a>
<ul>
<li class="toclevel-2 tocsection-4"><a href="#Studio_albums"><span class="tocnumber">3.1</span> <span class="toctext">Studio albums</span></a></li>
<li class="toclevel-2 tocsection-5"><a href="#Singles"><span class="tocnumber">3.2</span> <span class="toctext">Singles</span></a></li>
</ul>
</li>
<li class="toclevel-1 tocsection-6"><a href="#Selected_filmography"><span class="tocnumber">4</span> <span class="toctext">Selected filmography</span></a></li>
<li class="toclevel-1 tocsection-7"><a href="#See_also"><span class="tocnumber">5</span> <span class="toctext">See also</span></a></li>
<li class="toclevel-1 tocsection-8"><a href="#References"><span class="tocnumber">6</span> <span class="toctext">References</span></a></li>
<li class="toclevel-1 tocsection-9"><a href="#External_links"><span class="tocnumber">7</span> <span class="toctext">External links</span></a></li>
</ul>
</div>

			<div class="address">
				<p>218 Grand Street</p>
				<p>New York, NY 10013</p>
				<p>Tel: 212-226-8039</p>
			</div>
		  </div>
		  
		  <center>
	 </a>
    </div>


<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Meat</h1>
<p>Brocolli and meat</p>

app/views/pages/home.html.erb
    <div class="container" style="margin-top: -100px;">
      <div class="page-header">
		<div class="jumbotron">
        <h1>MENU</h1>
		</jumbotron>
      </div>
    <div class="jumbotron" style="margin-top: -20px;">	
	  <span class="mw-headline" id="Personal_life"><p style="margin-top: -30px;"><h1>Appetizers</h1></p><hr></span>
		<div class="row">
		
              <div class="col-lg-3 col-md-3 col-sm-6">
               
                  <h3>Vegetable Spring Rolls(3)</h3>
                  <a href="/html/default.asp">HTML Tutorial</a><br>
                  <p style="color:green;">$5.00</p>
             
              </div>

              <div class="col-lg-3 col-md-3 col-sm-6">
				  
                  <h3>Dumplings(5)</h3>
				  <h4>(Steamed or Fried)</h4>
                  <a href="/cert/default.asp">HTML Certificate</a><br>
                  <p style="color:green;">$6.00</p>
				
              </div>        
            </div>  
					
			<br>
			<div class="row">
              <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="top10">
                  <h3>Top 10 Tutorials</h3>
                  <a href="/html/default.asp">HTML Tutorial</a><br>
                  <a href="/css/default.asp">CSS Tutorial</a><br>
                  <a href="/js/default.asp">JavaScript Tutorial</a><br>
                  <a href="/sql/default.asp">SQL Tutorial</a><br>
                  <a href="/php/default.asp">PHP Tutorial</a><br>
                  <a href="/jquery/default.asp">jQuery Tutorial</a><br>
                  <a href="/bootstrap/default.asp">Bootstrap Tutorial</a><br>
                  <a href="/angular/default.asp">Angular Tutorial</a><br>
                  <a href="/aspnet/default.asp">ASP.NET Tutorial</a><br>
                  <a href="/xml/default.asp">XML Tutorial</a><br>
                </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="top10">
                  <h3>Top 10 References</h3>
                  <a href="/tags/default.asp">HTML Reference</a><br>
                  <a href="/cssref/default.asp">CSS Reference</a><br>
                  <a href="/jsref/default.asp">JavaScript Reference</a><br>
                  <a href="/browsers/default.asp">Browser Statistics</a><br>
                  <a href="/jsref/dom_obj_document.asp">HTML DOM</a><br>
                  <a href="/php/php_ref_array.asp">PHP Reference</a><br>
                  <a href="/jquery/jquery_ref_selectors.asp">jQuery Reference</a><br>
                  <a href="/tags/ref_colornames.asp">HTML Colors</a><br>
                  <a href="/charsets/default.asp">HTML Character Sets</a><br>
                  <a href="/dom/dom_nodetype.asp">XML DOM</a><br>
                </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="top10">
                  <h3>Top 10 Examples</h3>
                  <a href="/html/html_examples.asp">HTML Examples</a><br>
                  <a href="/css/css_examples.asp">CSS Examples</a><br>
                  <a href="/js/js_examples.asp">JavaScript Examples</a><br>
                  <a href="/js/js_dom_examples.asp">HTML DOM Examples</a><br>
                  <a href="/php/php_examples.asp">PHP Examples</a><br>
                  <a href="/jquery/jquery_examples.asp">jQuery Examples</a><br>
                  <a href="/xml/xml_examples.asp">XML Examples</a><br>
                  <a href="/dom/dom_examples.asp">XML DOM Examples</a><br>
                  <a href="/asp/asp_examples.asp">ASP Examples</a><br>
                  <a href="/svg/svg_examples.asp">SVG Examples</a>
                </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="top10">
                  <h3>Web Certificates</h3>
                  <a href="/cert/default.asp">HTML Certificate</a><br>
                  <a href="/cert/default.asp">HTML5 Certificate</a><br>
                  <a href="/cert/default.asp">CSS Certificate</a><br>
                  <a href="/cert/default.asp">JavaScript Certificate</a><br>
                  <a href="/cert/default.asp">jQuery Certificate</a><br>
                  <a href="/cert/default.asp">PHP Certificate</a><br>
                  <a href="/cert/default.asp">Bootstrap Certificate</a><br>
                  <a href="/cert/default.asp">XML Certificate</a><br>
                  
                </div>
				
              </div>        
            </div>     

			
			

	</div>
  

  </div><!-- /.container -->

	

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
 <div class="page-header" style="margin-top: 0px;">
    <div class="jumbotron">
        <h1>MENU</h1>
    </jumbotron>
      </div>

<h1>Listing pins</h1>
<center>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>
<br>

<%= link_to 'New Pin', new_pin_path %>

    <div class="container" style="margin-top: -0px;">
      <div class="page-header">
    <div class="jumbotron">
        <h1>MENU</h1>
    </jumbotron>
      </div>
    <div class="jumbotron" style="margin-top: -20px;">  
    <p style="margin-top: -30px;"><h1>Appetizers</h1></p><hr>
    <div class="row">
              <% @pins.reject{ |pin| !(pin.foodtype == "appetizer") }.each do |pin| %>
              <div class="col-lg-3 col-md-3 col-sm-6">
                  
                  <h3><%= pin.name %></h3>
                  <a href="/html/default.asp">HTML Tutorial</a><br>
                  <p style="color:green;"><%= pin.price %></p>
                 
                  
              </div>
              <% end %>

    </div>  

          
      <br>

  </div>
   <div class="jumbotron" style="margin-top: -20px;">  
    <p style="margin-top: -30px;"><h1>Soups</h1></p><hr>
<!--     <div class="row">
              <% @pins.reject{ |pin| !(pin.foodtype == "soup") }.each do |pin| %>
              <div class="col-lg-3 col-md-3 col-sm-6">
                  
                  <h3><%= pin.name %></h3>
                  <a href="/html/default.asp">HTML Tutorial</a><br>
                  <p style="color:green;"><%= pin.price %></p>
                 
                  
              </div>
              <% end %>

    </div>   -->
          
  <div class="bs-example" data-example-id="thumbnails-with-custom-content">
    <div class="row">
      <% @pins.reject{ |pin| !(pin.foodtype == "soup") }.each do |pin| %>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="thumbnail" style="background-color: rgba(0,0,0,.0);border-width: 4px; border-style:solid;border-color: #E0E0D1;">
          <img src="http://theculinarycook.com/wp-content/uploads/2012/04/types-of-soup.jpg" alt="Generic placeholder thumbnail">
          <div class="caption">
          <hr>
            <h3 style="font-size: 25px;color:white;"><%= pin.name %></h3><hr width="50%">
            <p style="color:#5CE62E;"><%= pin.price %></p>
            
          </div>
        </div>
      </div>
      <% end %>
      
    </div>
  </div><!-- /.bs-example -->
      <br> 

  </div><!-- /.container -->

  

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>